# Generated by Django 3.2.3 on 2021-06-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150)),
                ('etage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('ville', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('salaire', models.FloatField(max_length=100000)),
                ('id_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_info_app.depart')),
            ],
        ),
    ]
