# Generated by Django 3.2.3 on 2021-06-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_info_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='id_depart',
            new_name='depart',
        ),
    ]
